sudo: false
 
install:
  - node --version
  - npm --version
  - npm install -f elm@0.16.0 elm-test
  - export PATH="`pwd`/node_modules/.bin:$PATH"
  - (cd tests; elm-package install --yes)

script:
  - elm-make --yes
  - elm-test
