sudo: false

language: node_js
node_js: "5.1"
 
install:
  - node --version
  - npm --version
  - npm install -f elm@0.16.0 elm-test
  - export PATH="`pwd`/node_modules/.bin:$PATH"
  - (cd tests; elm-package install --yes)

script:
  - elm-make --yes
  - rsync -va elm-stuff/build-artifacts/ tests/elm-stuff/build-artifacts/
  - elm-test
